basePath: /moon
definitions:
  coin.BuyCoinRequest:
    properties:
      coinId:
        example: 1
        type: integer
      moon:
        example: 2
        type: number
      slippage:
        example: 5
        type: number
      thbt:
        example: 100
        type: number
      userId:
        example: XXX
        type: string
    type: object
  coin.Coin:
    properties:
      coinName:
        example: MOON
        type: string
      id:
        example: 1
        type: integer
      supply:
        example: 1000
        type: number
    type: object
  coin.History:
    properties:
      dateTime:
        example: 2021-04-01 10:00
        type: string
      moon:
        example: 0.2
        type: number
      number:
        example: 1
        type: integer
      rate:
        example: 1 MOON = 55 THBT | 0.01818181
        type: string
      thbt:
        example: 100
        type: number
      userId:
        example: AAA
        type: string
    type: object
  response.ErrResponse:
    properties:
      code:
        example: 400
        type: integer
      description:
        example: Please contact administrator for more information.
        type: string
      error:
        type: object
      title:
        example: Cannot register public key.
        type: string
    type: object
  response.Response:
    properties:
      code:
        example: 200
        type: integer
      data:
        type: object
      title:
        example: Register key success.
        type: string
    type: object
host: localhost:9090
info:
  contact:
    email: k.apiwattanawong@gmail.com
    name: Khanapat.A
    url: http://www.swagger.io/support
  description: Moon Coin for exchange.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Moon Coin
  version: "1.0"
paths:
  /buy:
    post:
      consumes:
      - application/json
      description: Method for buying coin.
      parameters:
      - description: object body to create coin
        in: body
        name: BuyCoinRequest
        required: true
        schema:
          $ref: '#/definitions/coin.BuyCoinRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrResponse'
      summary: Buy Coin
      tags:
      - Coin
  /history:
    get:
      consumes:
      - application/json
      description: Method for searching history transaction.
      parameters:
      - description: History Date From
        in: query
        name: from
        type: string
      - description: History Date To
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/coin.History'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrResponse'
      summary: Get History Transaction
      tags:
      - Coin
  /reset:
    get:
      consumes:
      - application/json
      description: Method for setting up supply coin.
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrResponse'
      summary: reset and setup supply coin
      tags:
      - Coin
  /supply:
    get:
      consumes:
      - application/json
      description: Method for getting coin supply.
      parameters:
      - description: Coin ID
        in: query
        name: id
        type: string
      - description: Coin Name
        in: query
        name: coinName
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/coin.Coin'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrResponse'
      summary: Get Coin Supply
      tags:
      - Coin
schemes:
- http
- https
swagger: "2.0"
